### ISSUE TITLE
`invalid number` error with intel T2330 CPU 

### ISSUE THREAD

**Issue by trappedinspacetime** [tiziw/iuvolt#7] opened 2018-03-28 17:25 UTC
First of all, thank you for sharing this tool.
I am running Ubuntu 16.04 on an old 5715Z Acer laptop. I just tried your tool but it fails with the following error: 

       iuvolt -90 -80 -90
       /usr/bin/iuvolt: line 6: printf: -92.160: invalid number
       wrmsr: CPU 0 cannot set MSR 0x00000150 to 0x0000000800000110
       wrmsr: CPU 0 cannot set MSR 0x00000150 to 0x8000001000000000
       rdmsr: CPU 0 cannot read MSR 0x00000150
       /usr/bin/iuvolt: line 49: [: ==: unary operator expected
       wrote failed, got: 
       /usr/bin/iuvolt: line 6: printf: -81.920: invalid number
       wrmsr: CPU 0 cannot set MSR 0x00000150 to 0x0000000800001110
       wrmsr: CPU 0 cannot set MSR 0x00000150 to 0x8000011000000000
       rdmsr: CPU 0 cannot read MSR 0x00000150
       /usr/bin/iuvolt: line 49: [: ==: unary operator expected
       wrote failed, got: 
       /usr/bin/iuvolt: line 6: printf: -92.160: invalid number
       wrmsr: CPU 0 cannot set MSR 0x00000150 to 0x0000000800002110
       wrmsr: CPU 0 cannot set MSR 0x00000150 to 0x8000021000000000
       rdmsr: CPU 0 cannot read MSR 0x00000150
       /usr/bin/iuvolt: line 49: [: ==: unary operator expected
       wrote failed, got: 

       iuvolt -90.8 -80.1 -90.8
       /usr/bin/iuvolt: line 6: printf: -92.979: invalid number
       wrmsr: CPU 0 cannot set MSR 0x00000150 to 0x0000000800000110
       wrmsr: CPU 0 cannot set MSR 0x00000150 to 0x8000001000000000
       rdmsr: CPU 0 cannot read MSR 0x00000150
       /usr/bin/iuvolt: line 49: [: ==: unary operator expected
       wrote failed, got: 
       /usr/bin/iuvolt: line 6: printf: -82.022: invalid number
       wrmsr: CPU 0 cannot set MSR 0x00000150 to 0x0000000800001110
       wrmsr: CPU 0 cannot set MSR 0x00000150 to 0x8000011000000000
       rdmsr: CPU 0 cannot read MSR 0x00000150
       /usr/bin/iuvolt: line 49: [: ==: unary operator expected
       wrote failed, got: 
       /usr/bin/iuvolt: line 6: printf: -92.979: invalid number
       wrmsr: CPU 0 cannot set MSR 0x00000150 to 0x0000000800002110
       wrmsr: CPU 0 cannot set MSR 0x00000150 to 0x8000021000000000
       rdmsr: CPU 0 cannot read MSR 0x00000150
       /usr/bin/iuvolt: line 49: [: ==: unary operator expected
       wrote failed, got:

**Comment by tiziw** [comment] 2018-04-01 17:56
This is a localisation issue, I've pushed a fix to the main branch. Add 'LC_NUMERIC=C ' right before printf in the first line of the round function or just copy and paste the script directly from the repo into the iuvolt script file on your system. Please reply to let us know whether the issue is fixed.

**Comment by trappedinspacetime** [comment] 2018-04-01 21:21
I just tried your latest fix, unfortunately it didn't work, you think it's a `locale` issue? I forgot to mention, I enabled multiarch support in my distro, so I am running a 32 bit installation with 64  bit kernel. Does it matter?

**Comment by tiziw** [comment] 2018-04-02 23:11
Can you print the output of the command 'locale' or set it to english using "export LOCALE=en_US.UTF-8"? Did you double check whether the iuvolt script in /usr/bin has the LC_NUMERIC=C in it? Did the error differ or is it the same. Architecture should have nothing to do with the error, if you google the printf error it'll show that it's a locale problem. 

I just remember that this issue was reported and fixed before, it's strange however that it still occurs on your machine. Are you sure you're running the latest version of the script?

**Comment by trappedinspacetime** [comment] 2018-04-03 09:18
LANG=C.UTF-8
     LANGUAGE=tr_TR.UTF-8
     LC_CTYPE="C.UTF-8"
     LC_NUMERIC="C.UTF-8"
     LC_TIME="C.UTF-8"
     LC_COLLATE="C.UTF-8"
     LC_MONETARY="C.UTF-8"
     LC_MESSAGES="C.UTF-8"
     LC_PAPER="C.UTF-8"
     LC_NAME="C.UTF-8"
     LC_ADDRESS="C.UTF-8"
     LC_TELEPHONE="C.UTF-8"
     LC_MEASUREMENT="C.UTF-8"
     LC_IDENTIFICATION="C.UTF-8"
     LC_ALL=C.UTF-8

I checked out the script in `/usr/bin/iuvolt` it has the `LC_NUMERIC=C`
I opened  `sudo su` then ran 

    chmod +x /usr/bin/iuvolt
    export LOCALE=en_US.UTF-8
    export LANG=en_US.UTF-8
    export LANGUAGE=en_US.UTF-8
    export LC_ALL=en_US.UTF-8
      iuvolt -90 -80 -90
      wrmsr: CPU 0 cannot set MSR 0x00000150 to 0x80000011f4800000
      wrmsr: CPU 0 cannot set MSR 0x00000150 to 0x8000001000000000
      rdmsr: CPU 0 cannot read MSR 0x00000150
      /usr/bin/iuvolt: line 49: [: ==: unary operator expected
      wrote failed, got: 
      wrmsr: CPU 0 cannot set MSR 0x00000150 to 0x80000111f5c00000
      wrmsr: CPU 0 cannot set MSR 0x00000150 to 0x8000011000000000
      rdmsr: CPU 0 cannot read MSR 0x00000150
      /usr/bin/iuvolt: line 49: [: ==: unary operator expected
      wrote failed, got: 
      wrmsr: CPU 0 cannot set MSR 0x00000150 to 0x80000211f4800000
      wrmsr: CPU 0 cannot set MSR 0x00000150 to 0x8000021000000000
      rdmsr: CPU 0 cannot read MSR 0x00000150
      /usr/bin/iuvolt: line 49: [: ==: unary operator expected
      wrote failed, got:

**Comment by tiziw** [comment] 2018-04-03 16:37
Alright, the error has changed. I've tested the script myself on an old laptop with an Intel Core 2 Duo P8600 and I got the same error as you did. This means that first, you had the localisation problem, but after it was fixed the script still didnt work as the model is too old apparently and doesn't support the method we use for undervolting. I haven't looked into what the oldest generation of Intel CPUs that can be undervolted, but it can be that older CPUs use a different register or another format.

I'll have to make the script fail gracefully in case the MSR registers can't be written and make it that it gives a more meaningful error. Sorry that the script didn't work for your scenario and thanks for your time. Maybe in the future I or someone else can look into undervolting with older CPUs, atleast to have it clear which models are supported and whether it's possible in linux.

**Comment by trappedinspacetime** [comment] 2018-04-03 17:19
Thank you for all your help. I didn't know that I could undervolt CPUs via some internal instructions. Nice hack. I also don't have time and programming skill in that scope. 
You responded to me and provided info.
I hope somebody help improve your script.
Regards

**Comment by tiziw** [comment] 2018-04-04 00:52
I've looked further into the subject and I've found that CPUs before the 3rd i-core generation, such as Core 2 Duo and your CPU work differently and their method of undervolting also works differently. Undervolting those CPUs has already been done in linux, but it's not as easy as writing a voltage to a register. [Here](https://wiki.archlinux.org/index.php/PHC) is an explanation on how to get it working, apparently it requires a special kernel module to work, which requires either a patched kernel or it can be loaded with DKMS. It doesn't work with voltages either, but with voltage identifiers, which are some kind of factor that decide what voltage is used for a certain clock. With the current method you just give as parameter what undervolt amount you want without any kind of calculations, however this is not the case with older CPUs.

[Here's](http://developers-club.com/posts/228233/) an article that explains very well how it really works.

I think the PHC ArchWiki page is your best shot at undervolting your CPU. If it were something as simple as writing something to an MSR register I'd have tried to add it to the script, however this is not the case, plus it's already been done. The page states that you have to install the intel-phc package, which has the required module in it, run a script that'll test what voltages are safe, then save them and they'll be loaded on startup. Make sure you follow the instructions correctly, especially regarding dkms part. The gains are well worth it from what I read as it can reduce heat and wattage significantly.

Good luck with undervolting!

**Closed as completed by tiziw** 2018-04-04 00:52 UTC
